[metadata]
name = macvert
version = 0.1.0
author = Eric Milan
license = MIT
long_description = file: README.rst
long_description_content_type = text/x-rst
url = https://github.com/emilan21/macvert

[options]
packages = find:
python_requires = >=3.10

[options.packages.find]
exclude =
    macvert.tests*

[options.extras_require]
web = Flask>=3.0

[options.entry_points]
console_scripts =
    macvert = macvert.cli:main
